
trigger:
  batch: true
  branches:
    include:
    - '*'

  paths:
    exclude:
      - .github/*

stages:
- stage: onPush
  jobs:
  - job: onPushJob
    pool:
      vmImage: 'ubuntu-22.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
        python -m pip install --upgrade pip
        pip install git+https://https://github.com/databricks/cli/releases@v0.209.1
      displayName: 'Install dependencies'

    - script: |
        cd deploy
        unzip spark-monitoring_1.0.0.jar.zip
        ls
        cd ..
        databricks workspace import-dir deploy /Shared/rob-test 
        # python deploy/deploy.py  --branch_name $(Build.SourceBranchName) --pr_branch $(System.PullRequest.SourceBranch)
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Deploy to Databricks workspace'